name: Lesson 20â€“21 Cucumber + Allure

on:
  push:
    branches: [main, Lesson22]
  pull_request:
    branches: [main]

permissions:
  contents: write
  checks: write
  pull-requests: write
  actions: read
  pages: write
  id-token: write

jobs:
  cucumber-allure:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      BUILD_FOLDER: ./lesson20-21-cucumber.js-Allure

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.BUILD_FOLDER }}

      - name: Install Playwright Browsers
        run: npx playwright install
        working-directory: ${{ env.BUILD_FOLDER }}

      - name: Run Cucumber tests
        run: npm test
        working-directory: ${{ env.BUILD_FOLDER }}
        env:
          CI: true
        continue-on-error: true

      - name: List allure-results
        run: |
          echo "Listing allure-results folder:"
          ls -la ./reports/allure-results || echo "Folder not found"
        working-directory: ${{ env.BUILD_FOLDER }}

      - name: Generate Allure Single-file report
        if: ${{ success() || always() }}
        run: |
          if [ -d ./reports/allure-results ] && [ "$(ls -A ./reports/allure-results)" ]; then
            echo "Generating Allure single-file report..."
            npx allure generate ./reports/allure-results --single-file --clean -o ./reports/allure-report-single-file
          else
            echo "No allure-results found, skipping report generation."
          fi
        working-directory: ${{ env.BUILD_FOLDER }}

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-single-file
          path: ${{ env.BUILD_FOLDER }}/reports/allure-report-single-file
          retention-days: 30

