name: Lesson 18â€“19 Playwright Tests

on:
  push:
    branches: [ main, Lesson22 ]
  pull_request:
    branches: [ main ]

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      BUILD_FOLDER: ./lesson18-19-Playwright

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.BUILD_FOLDER }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        working-directory: ${{ env.BUILD_FOLDER }}

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ${{ env.BUILD_FOLDER }}
        env:
          CI: true
        continue-on-error: true

      - name: Verify JSON report exists
        run: |
          ls -la test-results
          cat test-results/results.json
        working-directory: ${{ env.BUILD_FOLDER }}

      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: ${{ env.BUILD_FOLDER }}/test-results/results.json
          report-tag: 'Test Results Summary'
          job-summary: true
          create-comment: false
          icon-style: octicons

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: |
            ${{ env.BUILD_FOLDER }}/test-results
            ${{ env.BUILD_FOLDER }}/playwright-report
          retention-days: 14